routes/web.php
<?php

use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\ExamController;
use App\Http\Controllers\Admin\ExamQuestionController;
use App\Http\Controllers\Admin\FilesController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\PersonalMessageController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\VideoController;
use App\Http\Controllers\Admin\ExamInstanceController;
use App\Http\Controllers\HomepageController;
use App\Http\Controllers\StudentCoursesController;
use App\Http\Controllers\StudentExamController;
use App\Http\Controllers\StudentHomeController;
use App\Http\Controllers\StudentLoginController;
use App\Http\Controllers\StudentPersonalMessageController;
use App\Http\Controllers\StudentVideosController;
use Illuminate\Support\Facades\Route;

// Web Routes
Route::get('/', [HomepageController::class, 'index'])->name('index');
Route::post('contact', [HomepageController::class, 'email'])->name('contact.post');

// Admin Login routes
Route::group(['as' => 'ogrenci.', 'prefix' => 'ogrenci-paneli', 'middleware' => 'guest'], function ()
{
    Route::get('giris', [StudentLoginController::class, 'login'])->name('login');
    Route::post('giris', [StudentLoginController::class, 'check'])->name('login.attempt');
});

Route::get('admin', [HomeController::class, 'index'])->name('admin.index');
// Admin Login routes
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'guest'], function ()
{
    Route::get('login', [LoginController::class, 'index'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login.attempt');
});

// Student routes
Route::group(['as' => 'ogrenci.', 'prefix' => 'ogrenci-paneli', 'middleware' => 'auth'], function ()
{
    Route::get('', [StudentHomeController::class, 'index'])->name('index');
    Route::get('kurslar', [StudentCoursesController::class, 'index'])->name('courses.index');
    Route::get('kurslar/{course}/video/{video}', [StudentVideosController::class, 'show'])->name('videos.show');

    Route::get('sinavlar', [StudentExamController::class, 'index'])->name('exams.index');
    Route::get('sinavlar/{examInstance}/sonuc', [StudentExamController::class, 'show'])->name('exams.show');
    Route::get('sinavlar/{exam}/katil', [StudentExamController::class, 'join'])->name('exams.join');
    Route::post('sinavlar/bitir', [StudentExamController::class, 'finish'])->name('exams.finish');

    Route::get('soru-sor', [StudentPersonalMessageController::class, 'index'])->name('ask.index');
    Route::post('soru-sor', [StudentPersonalMessageController::class, 'store'])->name('ask.store');

    Route::post('cikis', [StudentLoginController::class, 'logout'])->name('logout');
});

// Admin Routes
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => ['auth', 'role:Admin']], function ()
{
    Route::resource('courses', CourseController::class);
    Route::resource('videos', VideoController::class);
    Route::resource('exams', ExamController::class);

    Route::get('exams/{exam}/instance', [ExamInstanceController::class, 'index'])->name('exams.instance.create');
    Route::post('exams/{exam}/instance', [ExamInstanceController::class, 'store'])->name('exams.instance.store');

    Route::post('exams/{exam}/questions/copy', [ExamQuestionController::class, 'copy'])->name('exams.question.copy');
    Route::resource('exams.questions', ExamQuestionController::class);

    Route::resource('users', UserController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('messages', PersonalMessageController::class);
    Route::post('messages/{thread}', [PersonalMessageController::class, 'store'])->name('messages.store');

    Route::get('roles/{role?}/permissions', [RoleController::class, 'permissions'])->name('roles.permissions.view');
    Route::post('roles/{role?}/permissions', [RoleController::class, 'storePermissions'])->name('roles.permissions.store');

    Route::post('upload', [FilesController::class, 'store'])->name('file.upload');
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends \Spatie\Permission\Models\Role
{
    protected $guard_name = '*';
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\PermissionCategory;
use App\Models\Role;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    public function index()
    {
        $roles = Role::all();
        return view('admin.roles.index', ['roles' => $roles]);
    }

    public function create()
    {
        return view('admin.roles.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, ['name' => 'required|unique:roles', 'description' => 'nullable']);

        $role = new Role();
        $role->name = $request->name;
        $role->description = $request->description;
        $role->guard_name = '*';
        $role->save();

        return back()->withInput()->with('status', 'Başarıyla eklendi!');
    }

    public function show(Role $role)
    {
        //
    }

    public function edit(Role $role)
    {
        return view('admin.roles.edit', ['role' => $role]);
    }

    public function update(Request $request, Role $role)
    {
        $this->validate($request, ['name' => 'required|unique:roles,name,' . $role->id, 'description' => 'nullable']);

        $role->update([
            'name' => $request->name,
            'description' => $request->description
        ]);

        return response()->redirectToRoute('admin.roles.index')->with('status', 'Başarıyla düzenlendi!');
    }

    public function destroy(Role $role)
    {
        $role->delete();

        return response()->json(['success' => true, 'message' => 'İşlem Başarılı']);
    }

    public function permissions(Role $role)
    {
        $permission_categories = PermissionCategory::all();

        return view('admin.roles.permissions', ['role' => $role, 'permission_categories' => $permission_categories]);
    }

    public function storePermissions(Request $request, Role $role)
    {
        $permissions = $request->get('permissions');

        $role->syncPermissions($permissions);

        return response()->redirectToRoute('admin.roles.index')->with('status', 'Başarıyla düzenlendi!');
    }
}

resources/views/admin/roles/edit.blade.php
@extends('admin.app')

@section('content')
    <div class="right-side">
        <section class="dashboard-content users">
            <div class="panel-heading">
                <h2><i class="fas fa-sign-in-alt"></i>Rol Düzenle</h2>
            </div>
            <div class="user-add black-bg">
                <div class="form-one">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('admin.roles.update', $role) }}" method="post">
                        @method('PUT')
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="name">Başlık</label>
                                    <input type="text" name="name" id="name"
                                           value="{{ $role->name }}" class="style-one">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="description">Açıklama</label>
                                    <input type="text" name="description" id="description"
                                           value="{{ $role->description }}" class="style-one">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group text-right">
                                <input type="hidden" name="form" value="duzenle">
                                <input type="submit" value="Düzenle" class="btn-one">
                            </div>
                        </div>
                        <input type="hidden" name="type" value="role">
                    </form>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('admin.app')
<?php /* @var \App\Models\Role[] $role */ ?>
@section('content')
    <div class="right-side">
        <section class="dashboard-content users">
            <div class="panel-heading">
                <h2><i class="fas fa-sign-in-alt"></i>Yetkiler</h2>
            </div>
            @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="user-add black-bg">
                <div class="form-one">
                    <div class="section-heading">
                        <a data-toggle="collapse" href="#collapseAddForm" role="button" aria-expanded="{{ $errors->any() ? 'true' : 'false' }}" aria-controls="collapseAddForm">
                            Rol Ekle
                        </a>
                    </div>
                    <form action="{{ route('admin.roles.store') }}" method="post" enctype="multipart/form-data" id="collapseAddForm"
                          class="collapse{{ $errors->any() ? ' show' : ''}}">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="name">İsim</label>
                                    <input type="text" name="name" id="name" class="style-one" required>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="description">Açıklama</label>
                                    <textarea id="description" name="description" class="style-one"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group text-right">
                                <input type="hidden" name="form" value="ekle">
                                <input type="submit" value="Ekle" class="btn-one">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="table-one black-bg">
                <div class="section-heading">
                    Haber Tablosu
                </div>
                <table class="datatable table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>Rol</th>
                        <th>Açıklama</th>
                        <th>İşlemler</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($roles as $role)
                        <tr>
                            <td>{{ $role->name }}</td>
                            <td>{{ $role->description }}</td>
                            <td class="text-right">
                                <a href="{{ route('admin.roles.permissions.view', $role) }}" class="btn-one accept-btn">Yetkiler</a>
                                <a href="{{ route('admin.roles.edit', $role) }}" class="btn-one edit-btn">Düzenle</a>
                                <a href="javascript:void(0)" class="btn-one delete-btn" onclick="deleteSubItem(this)"
                                   data-url="{{ route('admin.roles.destroy', $role) }}">Sil</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/roles/permissions.blade.php
@extends('admin.app')

@section('content')
    <div class="right-side">
        <section class="dashboard-content users">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-10"><h2><i class="fas fa-sign-in-alt"></i>Yetki Düzenle</h2>
                    </div>
                    <div class="col-md-2 text-right">
                        <button class="btn-one" form="permissionForm">KAYDET</button>
                    </div>
                </div>
            </div>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{ route('admin.roles.permissions.store', $role) }}" method="post" id="permissionForm">
                @csrf

                <div class="row">
                    @foreach ($permission_categories as $permission_category)

                        <div class="col-md-4">
                            <div class="user-add black-bg">
                                <div class="form-one">
                                    <div class="section-heading">
                                        {{ $permission_category->name }}
                                    </div>

                                    <div class="kt-widget2">
                                        @foreach($permission_category->permissions as $perm)
                                            <?php
                                            $per_found = null;

                                            if (isset($role))
                                            {
                                                $per_found = $role->hasPermissionTo($perm->name);
                                            }
                                            ?>

                                            <div class="form-group">
                                                <label>{{ $perm->description ?? $perm->name }}</label>
                                                <input data-category-id="{{ $permission_category->id }}" type="checkbox" name="permissions[]"
                                                       value="{{ $perm->name }}"{{ $per_found ? ' checked' : '' }}>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </form>
        </section>
    </div>
@endsection