routes/web.php
<?php

use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\ExamController;
use App\Http\Controllers\Admin\ExamQuestionController;
use App\Http\Controllers\Admin\FilesController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\PersonalMessageController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\VideoController;
use App\Http\Controllers\Admin\ExamInstanceController;
use App\Http\Controllers\HomepageController;
use App\Http\Controllers\StudentCoursesController;
use App\Http\Controllers\StudentExamController;
use App\Http\Controllers\StudentHomeController;
use App\Http\Controllers\StudentLoginController;
use App\Http\Controllers\StudentPersonalMessageController;
use App\Http\Controllers\StudentVideosController;
use Illuminate\Support\Facades\Route;

// Web Routes
Route::get('/', [HomepageController::class, 'index'])->name('index');
Route::post('contact', [HomepageController::class, 'email'])->name('contact.post');

// Admin Login routes
Route::group(['as' => 'ogrenci.', 'prefix' => 'ogrenci-paneli', 'middleware' => 'guest'], function ()
{
    Route::get('giris', [StudentLoginController::class, 'login'])->name('login');
    Route::post('giris', [StudentLoginController::class, 'check'])->name('login.attempt');
});

Route::get('admin', [HomeController::class, 'index'])->name('admin.index');
// Admin Login routes
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'guest'], function ()
{
    Route::get('login', [LoginController::class, 'index'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login.attempt');
});

// Student routes
Route::group(['as' => 'ogrenci.', 'prefix' => 'ogrenci-paneli', 'middleware' => 'auth'], function ()
{
    Route::get('', [StudentHomeController::class, 'index'])->name('index');
    Route::get('kurslar', [StudentCoursesController::class, 'index'])->name('courses.index');
    Route::get('kurslar/{course}/video/{video}', [StudentVideosController::class, 'show'])->name('videos.show');

    Route::get('sinavlar', [StudentExamController::class, 'index'])->name('exams.index');
    Route::get('sinavlar/{examInstance}/sonuc', [StudentExamController::class, 'show'])->name('exams.show');
    Route::get('sinavlar/{exam}/katil', [StudentExamController::class, 'join'])->name('exams.join');
    Route::post('sinavlar/bitir', [StudentExamController::class, 'finish'])->name('exams.finish');

    Route::get('soru-sor', [StudentPersonalMessageController::class, 'index'])->name('ask.index');
    Route::post('soru-sor', [StudentPersonalMessageController::class, 'store'])->name('ask.store');

    Route::post('cikis', [StudentLoginController::class, 'logout'])->name('logout');
});

// Admin Routes
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => ['auth', 'role:Admin']], function ()
{
    Route::resource('courses', CourseController::class);
    Route::resource('videos', VideoController::class);
    Route::resource('exams', ExamController::class);

    Route::get('exams/{exam}/instance', [ExamInstanceController::class, 'index'])->name('exams.instance.create');
    Route::post('exams/{exam}/instance', [ExamInstanceController::class, 'store'])->name('exams.instance.store');

    Route::post('exams/{exam}/questions/copy', [ExamQuestionController::class, 'copy'])->name('exams.question.copy');
    Route::resource('exams.questions', ExamQuestionController::class);

    Route::resource('users', UserController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('messages', PersonalMessageController::class);
    Route::post('messages/{thread}', [PersonalMessageController::class, 'store'])->name('messages.store');

    Route::get('roles/{role?}/permissions', [RoleController::class, 'permissions'])->name('roles.permissions.view');
    Route::post('roles/{role?}/permissions', [RoleController::class, 'storePermissions'])->name('roles.permissions.store');

    Route::post('upload', [FilesController::class, 'store'])->name('file.upload');
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');
});

resources/views/student/partials/footer.blade.php
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Sertifika Denizi &copy; 2022 | <a href="https://statikyazilim.com.tr" target="_blank">Statik Yazılım</a></span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

</div>
<!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
</div>
<!-- Bootstrap core JavaScript-->
<script src="{{ asset('panel/vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('panel/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- Core plugin JavaScript-->
<script src="{{ asset('panel/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

<!-- Custom scripts for all pages-->
<script src="{{ asset('panel/js/sb-admin-2.js') }}"></script>



@stack('scripts')

</body>

</html>

resources/views/student/partials/header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Sertifika Denizi | Öğrenci Paneli</title>

    <!-- Custom fonts for this template-->
    <link href="{{ asset('panel/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{ asset('/panel/css/sb-admin-2.css') }}" rel="stylesheet">
    <link href="{{ asset('/panel/css/custom.css') }}" rel="stylesheet">

</head>

resources/views/student/partials/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-secondary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ route('ogrenci.index') }}">
        <img id="logo" src="{{ asset('img/Sertifika-dunyas.png') }}" alt="logo">
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item ">
        <a class="nav-link" href="{{ route('ogrenci.index') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Ana Sayfa</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">


    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="{{ route('ogrenci.courses.index') }}" >
            <i class="fas fa-fw fa-chalkboard"></i>
            <span>Kurslarım</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link collapsed" href="{{ route('ogrenci.exams.index') }}">
            <i class="fas fa-fw fa-university"></i>
            <span>Sınavlarım</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link collapsed" href="{{ route('ogrenci.ask.index') }}">
            <i class="fas fa-fw fa-question"></i>
            <span>Hocaya Soru Sor</span>
        </a>
    </li>
{{--    <li class="nav-item">
        <a class="nav-link collapsed" href="/odemeler" >
            <i class="fas fa-fw fa-credit-card"></i>
            <span>Ödemelerim</span>
        </a>
    </li>--}}


</ul>
<!-- End of Sidebar -->

resources/views/student/partials/topbar.blade.php
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="javascript:void(0)" id="userDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ auth()->user()->name }}</span>
                <img class="img-profile rounded-circle"
                     src="{{ asset('img/undraw_profile.svg') }}">
            </a>

            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                 aria-labelledby="userDropdown">
                <!-- <a class="dropdown-item" href="#">
                   <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                   Profile
               </a>
               <a class="dropdown-item" href="#">
                   <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                   Settings
               </a>
               <a class="dropdown-item" href="#">
                   <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                   Activity Log
               </a>-->
                <a class="dropdown-item" href="{{ route('ogrenci.logout') }}"
                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">

                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Çıkış
                    <form id="logout-form" action="{{ route('ogrenci.logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </a>
            </div>
        </li>

    </ul>

</nav>
<!-- End of Topbar -->