routes/web.php
<?php

use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\ExamController;
use App\Http\Controllers\Admin\ExamQuestionController;
use App\Http\Controllers\Admin\FilesController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\PersonalMessageController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\VideoController;
use App\Http\Controllers\Admin\ExamInstanceController;
use App\Http\Controllers\HomepageController;
use App\Http\Controllers\StudentCoursesController;
use App\Http\Controllers\StudentExamController;
use App\Http\Controllers\StudentHomeController;
use App\Http\Controllers\StudentLoginController;
use App\Http\Controllers\StudentPersonalMessageController;
use App\Http\Controllers\StudentVideosController;
use Illuminate\Support\Facades\Route;

// Web Routes
Route::get('/', [HomepageController::class, 'index'])->name('index');
Route::post('contact', [HomepageController::class, 'email'])->name('contact.post');

// Admin Login routes
Route::group(['as' => 'ogrenci.', 'prefix' => 'ogrenci-paneli', 'middleware' => 'guest'], function ()
{
    Route::get('giris', [StudentLoginController::class, 'login'])->name('login');
    Route::post('giris', [StudentLoginController::class, 'check'])->name('login.attempt');
});

Route::get('admin', [HomeController::class, 'index'])->name('admin.index');
// Admin Login routes
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'guest'], function ()
{
    Route::get('login', [LoginController::class, 'index'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login.attempt');
});

// Student routes
Route::group(['as' => 'ogrenci.', 'prefix' => 'ogrenci-paneli', 'middleware' => 'auth'], function ()
{
    Route::get('', [StudentHomeController::class, 'index'])->name('index');
    Route::get('kurslar', [StudentCoursesController::class, 'index'])->name('courses.index');
    Route::get('kurslar/{course}/video/{video}', [StudentVideosController::class, 'show'])->name('videos.show');

    Route::get('sinavlar', [StudentExamController::class, 'index'])->name('exams.index');
    Route::get('sinavlar/{examInstance}/sonuc', [StudentExamController::class, 'show'])->name('exams.show');
    Route::get('sinavlar/{exam}/katil', [StudentExamController::class, 'join'])->name('exams.join');
    Route::post('sinavlar/bitir', [StudentExamController::class, 'finish'])->name('exams.finish');

    Route::get('soru-sor', [StudentPersonalMessageController::class, 'index'])->name('ask.index');
    Route::post('soru-sor', [StudentPersonalMessageController::class, 'store'])->name('ask.store');

    Route::post('cikis', [StudentLoginController::class, 'logout'])->name('logout');
});

// Admin Routes
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => ['auth', 'role:Admin']], function ()
{
    Route::resource('courses', CourseController::class);
    Route::resource('videos', VideoController::class);
    Route::resource('exams', ExamController::class);

    Route::get('exams/{exam}/instance', [ExamInstanceController::class, 'index'])->name('exams.instance.create');
    Route::post('exams/{exam}/instance', [ExamInstanceController::class, 'store'])->name('exams.instance.store');

    Route::post('exams/{exam}/questions/copy', [ExamQuestionController::class, 'copy'])->name('exams.question.copy');
    Route::resource('exams.questions', ExamQuestionController::class);

    Route::resource('users', UserController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('messages', PersonalMessageController::class);
    Route::post('messages/{thread}', [PersonalMessageController::class, 'store'])->name('messages.store');

    Route::get('roles/{role?}/permissions', [RoleController::class, 'permissions'])->name('roles.permissions.view');
    Route::post('roles/{role?}/permissions', [RoleController::class, 'storePermissions'])->name('roles.permissions.store');

    Route::post('upload', [FilesController::class, 'store'])->name('file.upload');
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');
});

app/Models/Admin/Exam.php
<?php

namespace App\Models\Admin;

use App\Models\ExamInstance;
use App\Models\ExamResult;
use Eloquent;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Exam extends Model
{
    use SoftDeletes;
    protected $guarded = ['id'];
    protected $appends = ['status_text'];

    public function getStatusTextAttribute()
    {
        if ($this->status)
        {
            return 'Açık';
        }
        else
        {
            return 'Kapalı';
        }
    }

    public function course()
    {
        return $this->belongsTo(Course::class);
    }

    public function questions()
    {
        return $this->hasMany(ExamQuestion::class)->orderBy('id');
    }

    public function instance()
    {
        return $this->hasOne(ExamInstance::class);
    }

    public function students()
    {
        return $this->hasManyThrough(ExamStudent::class, ExamInstance::class);
    }

    public function results()
    {
        return $this->hasManyThrough(ExamResult::class, ExamInstance::class);
    }

    public function currentUserResults()
    {
        return $this->hasManyThrough(ExamResult::class, ExamStudent::class, 'user_id', 'user_id');
    }
}

app/Http/Controllers/Admin/ExamController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreExamRequest;
use App\Models\Admin\Course;
use App\Models\Admin\Exam;

class ExamController extends Controller
{
    public function index()
    {
        $exams = Exam::all();
        $courses = Course::all();
        return view('admin.exams.index', ['exams' => $exams, 'courses' => $courses]);
    }

    public function store(StoreExamRequest $request)
    {
        $validatedData = $request->validated();

        $exam = new Exam($validatedData);
        $exam->save();

        return redirect()->route('admin.exams.instance.create', ['exam' => $exam]);
    }

    public function show(Exam $exam)
    {
        return view('admin.exams.show', compact('exam'));
    }

    public function edit(Exam $exam)
    {
        $courses = Course::all();
        return view('admin.exams.edit', ['exam' => $exam, 'courses' => $courses]);
    }

    public function update(StoreExamRequest $request, Exam $exam)
    {
        $validatedData = $request->validated();

        $exam->update($validatedData);

        return response()->redirectToRoute('admin.exams.index')->with('status', 'Başarıyla düzenlendi!');
    }

    public function destroy(Exam $exam)
    {
        $exam->delete();

        return response()->json(['success' => true, 'message' => 'İşlem Başarılı']);
    }
}

resources/views/admin/exams/questions/edit.blade.php
@extends('admin.app')

@section('content')
    <div class="right-side">
        <section class="dashboard-content users">
            <div class="panel-heading">
                <h2><i class="fas fa-sign-in-alt"></i>Soru Düzenle - {{ $question->question_text }}</h2>
            </div>
            <div class="user-add black-bg">
                <div class="form-one">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('admin.exams.questions.update', compact('exam', 'question')) }}" method="post">
                        @method('PUT')
                        @csrf
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="question_text">Soru</label>
                                    <input type="text" name="question_text" id="question_text" class="style-one" value="{{ $question->question_text }}" required>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-10"><label>Cevaplar</label></div>
                                        <div class="col-md-2"><label>Doğru Cevap</label></div>
                                    </div>
                                    @foreach ($question->answers as $answer)
                                    <div class="row mt-2">
                                        <div class="col-md-10"><input type="text" name="answers[{{ $answer->id }}]" value="{{ $answer->answer_text }}" class="style-one"></div>
                                        <div class="col-md-2"><input type="radio" name="trueAnswer" value="{{ $answer->id }}" {{ $answer->is_true ? ' checked' : '' }}></div>
                                    </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group text-right">
                                <input type="hidden" name="form" value="duzenle">
                                <input type="submit" value="Düzenle" class="btn-one">
                            </div>
                        </div>
                        <input type="hidden" name="type" value="announcement">
                    </form>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/exams/questions/index.blade.php
@extends('admin.app')
<?php /* @var \App\Models\Admin\Exam $exam */ ?>
<?php /* @var \App\Models\Admin\ExamQuestion[] $questions */ ?>
@section('content')
    <div class="right-side">
        <section class="dashboard-content users">
            <div class="panel-heading">
                <h2><i class="fas fa-sign-in-alt"></i>Sınavlar - <a href="{{ route('admin.exams.index') }}">{{ $exam->name }}</a> </h2>
            </div>
            @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="user-add black-bg">
                <div class="form-one">
                    <div class="section-heading">
                        <a data-toggle="collapse" href="#collapseAddForm" role="button" aria-expanded="{{ $errors->any() ? 'true' : 'false' }}" aria-controls="collapseAddForm">
                            Soru Ekle
                        </a>
                    </div>
                    <form action="{{ route('admin.exams.questions.store', $exam) }}" method="post" enctype="multipart/form-data" id="collapseAddForm"
                          class="collapse {{ $errors->any() ? ' show' : ''}}">
                        @csrf
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="question_text">Soru</label>
                                    <input type="text" name="question_text" id="question_text" class="style-one" required>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-10"><label>Cevaplar</label></div>
                                        <div class="col-md-2"><label>Doğru Cevap</label></div>
                                    </div>
                                    <div class="row mt-2">
                                        <div class="col-md-10"><input type="text" name="answers[]" class="style-one"></div>
                                        <div class="col-md-2"><input type="radio" name="trueAnswer[0]"></div>
                                    </div>
                                    <div class="row mt-2">
                                        <div class="col-md-10"><input type="text" name="answers[]" class="style-one"></div>
                                        <div class="col-md-2"><input type="radio" name="trueAnswer[1]"></div>
                                    </div>
                                    <div class="row mt-2">
                                        <div class="col-md-10"><input type="text" name="answers[]" class="style-one"></div>
                                        <div class="col-md-2"><input type="radio" name="trueAnswer[2]"></div>
                                    </div>
                                    <div class="row mt-2">
                                        <div class="col-md-10"><input type="text" name="answers[]" class="style-one"></div>
                                        <div class="col-md-2"><input type="radio" name="trueAnswer[3]"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group text-right">
                                <input type="hidden" name="form" value="ekle">
                                <input type="submit" value="Ekle" class="btn-one">
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="user-add black-bg">
                <div class="form-one">
                    <div class="section-heading">
                        <form method="post" action="{{ route('admin.exams.question.copy', $exam) }}">
                            @csrf
                            <select name="from">
                                @foreach ($exams as $exam2)
                                    <option value="{{ $exam2->id }}">{{ $exam2->name }}</option>
                                @endforeach
                            </select>
                            <input type="submit" class="btn-one" value="Soruları Kopyala">
                        </form>
                    </div>
                </div>
            </div>
            <div class="table-one black-bg">
                <div class="section-heading">
                    Soru Tablosu
                </div>
                <table class="datatable table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Soru</th>
                        <th>İşlemler</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($exam->questions as $i => $question)
                        <tr>
                            <td>{{ $i+1 }}</td>
                            <td>{{ $question->question_text }}</td>
                            <td class="text-right">
                                <a href="{{ route('admin.exams.questions.edit', ['exam' => $exam, 'question' => $question]) }}" class="btn-one edit-btn">Düzenle</a>
                                <a href="javascript:void(0)" class="btn-one delete-btn" onclick="deleteSubItem(this)"
                                   data-url="{{ route('admin.exams.questions.destroy', ['exam' => $exam, 'question' => $question]) }}">Sil</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </section>
    </div>
@endsection