routes/web.php
<?php

use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\ExamController;
use App\Http\Controllers\Admin\ExamQuestionController;
use App\Http\Controllers\Admin\FilesController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\PersonalMessageController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\VideoController;
use App\Http\Controllers\Admin\ExamInstanceController;
use App\Http\Controllers\HomepageController;
use App\Http\Controllers\StudentCoursesController;
use App\Http\Controllers\StudentExamController;
use App\Http\Controllers\StudentHomeController;
use App\Http\Controllers\StudentLoginController;
use App\Http\Controllers\StudentPersonalMessageController;
use App\Http\Controllers\StudentVideosController;
use Illuminate\Support\Facades\Route;

// Web Routes
Route::get('/', [HomepageController::class, 'index'])->name('index');
Route::post('contact', [HomepageController::class, 'email'])->name('contact.post');

// Admin Login routes
Route::group(['as' => 'ogrenci.', 'prefix' => 'ogrenci-paneli', 'middleware' => 'guest'], function ()
{
    Route::get('giris', [StudentLoginController::class, 'login'])->name('login');
    Route::post('giris', [StudentLoginController::class, 'check'])->name('login.attempt');
});

Route::get('admin', [HomeController::class, 'index'])->name('admin.index');
// Admin Login routes
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'guest'], function ()
{
    Route::get('login', [LoginController::class, 'index'])->name('login');
    Route::post('login', [LoginController::class, 'login'])->name('login.attempt');
});

// Student routes
Route::group(['as' => 'ogrenci.', 'prefix' => 'ogrenci-paneli', 'middleware' => 'auth'], function ()
{
    Route::get('', [StudentHomeController::class, 'index'])->name('index');
    Route::get('kurslar', [StudentCoursesController::class, 'index'])->name('courses.index');
    Route::get('kurslar/{course}/video/{video}', [StudentVideosController::class, 'show'])->name('videos.show');

    Route::get('sinavlar', [StudentExamController::class, 'index'])->name('exams.index');
    Route::get('sinavlar/{examInstance}/sonuc', [StudentExamController::class, 'show'])->name('exams.show');
    Route::get('sinavlar/{exam}/katil', [StudentExamController::class, 'join'])->name('exams.join');
    Route::post('sinavlar/bitir', [StudentExamController::class, 'finish'])->name('exams.finish');

    Route::get('soru-sor', [StudentPersonalMessageController::class, 'index'])->name('ask.index');
    Route::post('soru-sor', [StudentPersonalMessageController::class, 'store'])->name('ask.store');

    Route::post('cikis', [StudentLoginController::class, 'logout'])->name('logout');
});

// Admin Routes
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => ['auth', 'role:Admin']], function ()
{
    Route::resource('courses', CourseController::class);
    Route::resource('videos', VideoController::class);
    Route::resource('exams', ExamController::class);

    Route::get('exams/{exam}/instance', [ExamInstanceController::class, 'index'])->name('exams.instance.create');
    Route::post('exams/{exam}/instance', [ExamInstanceController::class, 'store'])->name('exams.instance.store');

    Route::post('exams/{exam}/questions/copy', [ExamQuestionController::class, 'copy'])->name('exams.question.copy');
    Route::resource('exams.questions', ExamQuestionController::class);

    Route::resource('users', UserController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('messages', PersonalMessageController::class);
    Route::post('messages/{thread}', [PersonalMessageController::class, 'store'])->name('messages.store');

    Route::get('roles/{role?}/permissions', [RoleController::class, 'permissions'])->name('roles.permissions.view');
    Route::post('roles/{role?}/permissions', [RoleController::class, 'storePermissions'])->name('roles.permissions.store');

    Route::post('upload', [FilesController::class, 'store'])->name('file.upload');
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');
});

resources/views/admin/partials/cropper.blade.php
<div class="modal fade" id="imageCropModal" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="editModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" style="max-width: 90%" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Resim Düzenle</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="cropper-container">
                    <img id="image-cropper">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                <button type="button" class="btn btn-primary" id="cropButton">Düzenle</button>
            </div>
        </div>
    </div>
</div>

@push('scripts')
    <script type="text/javascript">
        var $modal = $("#imageCropModal"),
            $cropper = $("#image-cropper"),
            $container = $(".cropper-container"),
            $uploadedImage, maxHeight, maxWidth, imageInput, model, modelId, attr, thumb;

        $(".toBeCropped").on("change", function (e) {
            var input = this;

            imageInput = $(this);
            maxHeight = imageInput.data('height');
            maxWidth = imageInput.data('width');
            model = imageInput.data('model');
            modelId= imageInput.data('model-id');
            attr = imageInput.data('attr');
            thumb = $("#" + attr + "InputThumb");


            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.readAsDataURL(input.files[0]);

                reader.onload = function (e) {
                    $uploadedImage = this.result;
                    $container.width(maxWidth).height(maxHeight);

                    $modal.modal("show");
                }
            }
        });

        $modal.on("shown.bs.modal", function (e) {
            $cropper.attr("src", $uploadedImage);

            $cropper.cropper({
                viewMode: 3,
                guides: false,
                rotatable: false,
                scalable: false,
                autoCropArea: 1,
                cropBoxResizable: false,
                toggleDragModeOnDblclick: false,
                dragMode: 'move',

                /*data: {
                    width: (maxWidth),
                    height: (maxHeight),
                },*/
            });
        }).on("hidden.bs.modal", function () {
            $cropper.cropper('destroy');
        });

        $("#cropButton").on("click", function () {
            var canvas;

            if ($cropper) {
                canvas = $cropper.data('cropper').getCroppedCanvas();
                if (imageInput) {
                    console.log(canvas);
                    thumb.attr("src", canvas.toDataURL());
                }

                canvas.toBlob(function (blob) {
                    var formData = new FormData(),
                        name = imageInput.val().split("\\\\").pop();

                    formData.append(attr, blob, name);
                    formData.append("attr", attr);
                    formData.append("model", model);
                    formData.append("modelId", modelId);

                    $.ajax("{{ route('admin.file.upload') }}", {
                        method: 'POST',
                        data: formData,
                        processData: false,
                        contentType: false,

                        success: function (e) {
                            console.log(e);

                            $("#" + imageInput.attr("id") + "Hidden").val(e.result.id);
                            $modal.modal('hide');
                        }
                    });
                });
            }
        });
    </script>
@endpush

resources/views/admin/partials/main-sidebar.blade.php
<div class="left-side">
    <div class="main-sidebar">
        <div class="top">
            <div class="logo">
                <img  src="{{ asset('img/Sertifika-dunyas.png') }}" alt="">
            </div>
        </div>
        <div class="main-menu">
            <ul>
                <x-admin-menu-item :url="route('admin.index')" title="Ana Sayfa" :icon="asset('admin_assets/assets/icons/dashboard.png')"></x-admin-menu-item>

                @if (Auth::check())
                    <x-admin-menu-item :url="route('admin.courses.index')" title="Kurslar" :icon="asset('admin_assets/assets/icons/group.png')"></x-admin-menu-item>
                    <x-admin-menu-item :url="route('admin.videos.index')" title="Videolar" :icon="asset('admin_assets/assets/icons/media.png')"></x-admin-menu-item>
                    <x-admin-menu-item :url="route('admin.exams.index')" title="Sınavlar" :icon="asset('admin_assets/assets/icons/mortarboard.png')"></x-admin-menu-item>
                    <x-admin-menu-item :url="route('admin.users.index')" title="Kullanıcılar" :icon="asset('admin_assets/assets/icons/user.png')"></x-admin-menu-item>
                    <x-admin-menu-item :url="route('admin.messages.index')" title="Mesajlar" :icon="asset('admin_assets/assets/icons/user.png')"></x-admin-menu-item>


{{--                    <x-admin-menu-item :url="route('admin.roles.index')" title="Yetkiler" :icon="asset('admin_assets/assets/icons/shield.png')"></x-admin-menu-item>--}}

                    <li>
                        <a href="{{ route('admin.logout') }}"
                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <img src="{{ asset('admin_assets/assets/icons/logout.png') }}" alt=""><span>Çıkış Yap</span>
                            <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </a>
                    </li>
                @endif
            </ul>
        </div>
        <div class="bottom">
            <div class="logo">
                <a href="https://statikyazilim.com.tr/">
                    <img src="{{ asset('admin_assets/assets/media/sy-yonetim-paneli.png') }}" alt="">
                </a>
            </div>
        </div>
    </div>
</div>